name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Foundry
        run: curl -L https://foundry.paradigm.xyz | bash

      - name: Build contracts
        run: forge build --sizes
        env:
          FOUNDRY_PROFILE: ci
          FOUNDRY_DISABLE_NIGHTLY_WARNING: 1

      - name: Run tests
        run: forge test -vvv
        env:
          FOUNDRY_PROFILE: ci
          FOUNDRY_DISABLE_NIGHTLY_WARNING: 1
